Models/AirQualityIndex.cs
namespace AirStation.Models
{
    public class AirQualityIndex
    {
        public IndexLevel So2IndexLevel { get; set; }

        public IndexLevel No2IndexLevel { get; set; }

        public IndexLevel CoIndexLevel { get; set; }

        public IndexLevel Pm10IndexLevel { get; set; }

        public IndexLevel Pm25IndexLevel { get; set; }

        public IndexLevel O3IndexLevel { get; set; }

        public IndexLevel C6H6IndexLevel { get; set; }

    }
}

Models/City.cs
namespace AirStation.Models
{
    public class City
    {
        public string Name { get; set; }
    }
}

Models/ErrorViewModel.cs
using System;

namespace AirStation.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/IndexLevel.cs
namespace AirStation.Models
{
    public class IndexLevel
    {
        public int Id { get; set; }
        public string IndexLevelName { get; set; }
    }
}

Models/MeasurementData.cs
using System.Collections.Generic;

namespace AirStation.Models
{
    public class MeasurementData
    {
        public string Key { get; set; }
        public List<Values> Values { get; set; }
    }
}

Models/MeasuringStation.cs
using System.Collections.Generic;

namespace AirStation.Models
{
    public class MeasuringStation
    {
        public int Id { get; set; }
        public string StationName { get; set; }
        public City City { get; set; }
        public string AddressStreet { get; set; }
        public List<TestStand> TestStands { get; set; }
        public AirQualityIndex AirQualityIndex { get; set; }
    }
}

Models/Param.cs
namespace AirStation.Models
{
    public class Param
    {
        public string ParamName { get; set; }
        public string ParamFormula { get; set; }
        public int IdParam { get; set; }
    }
}

Models/TestStand.cs
namespace AirStation.Models
{
    public class TestStand
    {
        public int Id { get; set; }
        public int StationId { get; set; }
        public Param Param { get; set; }

    }
}

Models/Values.cs
using System;

namespace AirStation.Models
{
    public class Values
    {
        public DateTime? Date { get; set; }
        public decimal? Value { get; set; }

    }
}

Controllers/DataController.cs
using AirStation.Services;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace AirStation.Controllers
{
    public class DataController : Controller
    {
        private readonly IApiService apiService;

        public DataController(IApiService apiService)
        {
            this.apiService = apiService;
        }
        public async Task<IActionResult> Data(int sensorId, int stationId)
        {
            var data = await apiService.GetSensorDataAsync(sensorId);
            TempData["stationId"] = stationId;
            return View(data);
        }
    }
}

Controllers/HomeController.cs
using AirStation.Services;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace AirStation.Controllers
{
    public class HomeController : Controller
    {
        private readonly IApiService apiService;

        public HomeController(IApiService apiService)
        {
            this.apiService = apiService;
        }

        public async Task<IActionResult> Index()
        {
            var stations = await apiService.GetStationsByCityAsync("Poznań");
            return View(stations);
        }
    }
}

Controllers/TestStandController.cs
using AirStation.Services;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace AirStation.Controllers
{
    public class TestStandController : Controller
    {
        private readonly IApiService apiService;

        public TestStandController(IApiService apiService)
        {
            this.apiService = apiService;
        }
        public async Task<IActionResult> Details(int stationId)
        {
            var measuringStation = await apiService.GetStationsByIdAsync(stationId);
            var testStands = await apiService.GetTestStandsAsync(stationId);
            var airQuality = await apiService.GetAirQualityAsync(stationId);
            measuringStation.TestStands = testStands;
            measuringStation.AirQualityIndex = airQuality;
            return View(measuringStation);
        }
    }
}

Views/Data/Data.cshtml
@model MeasurementData
@{
    ViewData["Title"] = "Dane pomiarowe";
}


<h1 class="space text-center" >Dane pomiarowe dla parametru @Model.Key </h1>


<div class="card">
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">Termin wykonania pomiaru [Data i godzina]</th>
                <th scope="col">Wartość pomiaru [μg/m3]</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var value in Model.Values)
            {
                if (value.Value.HasValue)
                {

                <tr>
                    <td>@value.Date</td>
                    <td>@Decimal.Round(value.Value.Value, 2)</td>
                </tr>
                }
            }
        </tbody>
    </table>
</div>

<div class="space">
    <a asp-controller="TestStand" asp-action="Details" asp-route-stationId="@TempData["stationId"]" class="btn btn-primary">Powrót do stacji</a>
</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "";
}
@model List<MeasuringStation>

<div class="text-center">
    <h1 class="display-4">Witamy!</h1>
    <h5 style="padding: 20px;">Prosimy wybrać jedną ze stacji z listy, aby uzyskać aktualne dane na temat jakości powietrza w Poznaniu.</h5>
</div>


<table class="table table-striped">
    <thead>Lista stacji:</thead>
    @foreach (var station in Model)
    {
        <tr>
            <td>
                <a asp-controller="TestStand" asp-action="Details" asp-route-stationId="@station.Id">@station.StationName</a>
            </td>
        </tr>
    }
</table>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] Stacje powietrzne</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Stacje Powietrzne</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                          
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Stacje powietrzne
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Shared/_QualityLevel.cshtml
@model MeasuringStation



@if (Model.AirQualityIndex.So2IndexLevel != null)
{
    <tr>
        <td>Dwutlenek siarki</td>
        <td>SO2</td>
        <td style="background-color: @(Model.AirQualityIndex.So2IndexLevel.Id > 2 ? "Tomato" :
                                            ((Model.AirQualityIndex.So2IndexLevel.Id) < 2 ? "LightGreen" : "DarkOrange"))">
            @Model.AirQualityIndex.So2IndexLevel.IndexLevelName
        </td>
    </tr>
}
@if (Model.AirQualityIndex.No2IndexLevel != null)
{
    <tr>
        <td>Dwutlenek azotu</td>
        <td>NO2</td>
        <td style="background-color: @(Model.AirQualityIndex.No2IndexLevel.Id > 2 ? "Tomato" :
                                            ((Model.AirQualityIndex.No2IndexLevel.Id) < 2 ? "LightGreen" : "DarkOrange"))">
            @Model.AirQualityIndex.No2IndexLevel.IndexLevelName
        </td>
    </tr>
}
@if (Model.AirQualityIndex.CoIndexLevel != null)
{
    <tr>
        <td>Tlenek węgla</td>
        <td>CO</td>
        <td style="background-color: @(Model.AirQualityIndex.CoIndexLevel.Id > 2 ? "Tomato" :
                                            ((Model.AirQualityIndex.CoIndexLevel.Id) < 2 ? "LightGreen" : "DarkOrange"))">
            @Model.AirQualityIndex.CoIndexLevel.IndexLevelName
        </td>
    </tr>
}
@if (Model.AirQualityIndex.Pm10IndexLevel != null)
{
    <tr>
        <td>Pył zawieszony PM10</td>
        <td>PM10</td>
        <td style="background-color: @(Model.AirQualityIndex.Pm10IndexLevel.Id > 2 ? "Tomato" :
                                            ((Model.AirQualityIndex.Pm10IndexLevel.Id) < 2 ? "LightGreen" : "DarkOrange"))">
            @Model.AirQualityIndex.Pm10IndexLevel.IndexLevelName
        </td>
    </tr>
}
@if (Model.AirQualityIndex.Pm25IndexLevel != null)
{
    <tr>
        <td>Pył zawieszony PM2.5</td>
        <td>PM2.5</td>
        <td style="background-color: @(Model.AirQualityIndex.Pm25IndexLevel.Id > 2 ? "Tomato" :
                                            ((Model.AirQualityIndex.Pm25IndexLevel.Id) < 2 ? "LightGreen" : "DarkOrange"))">
            @Model.AirQualityIndex.Pm25IndexLevel.IndexLevelName
        </td>
    </tr>
}
@if (Model.AirQualityIndex.O3IndexLevel != null)
{
    <tr>
        <td>Ozon</td>
        <td>O3</td>
        <td style="background-color: @(Model.AirQualityIndex.O3IndexLevel.Id > 2 ? "Tomato" :
                                            ((Model.AirQualityIndex.O3IndexLevel.Id) < 2 ? "LightGreen" : "DarkOrange"))">
            @Model.AirQualityIndex.O3IndexLevel.IndexLevelName
        </td>
    </tr>
}
@if (Model.AirQualityIndex.C6H6IndexLevel != null)
{

    <tr>
        <td>Benzen</td>
        <td>C6H6</td>
        <td style="background-color: @(Model.AirQualityIndex.C6H6IndexLevel.Id > 2 ? "Tomato" :
                                            ((Model.AirQualityIndex.C6H6IndexLevel.Id) < 2 ? "LightGreen" : "DarkOrange"))">
            @Model.AirQualityIndex.C6H6IndexLevel.IndexLevelName
        </td>
    </tr>
}

Views/TestStand/Details.cshtml
@model MeasuringStation
@{
    ViewData["Title"] = "Szczegóły stacji";
}


<h1 class="text-center">Szczegóły stacji  @Model.StationName</h1>


<div class="space">
    <h4>Informacje o stacji</h4>

</div>
<div class="card">
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">Numer stacji</th>
                <th scope="col">Nazwa stacji</th>
                <th scope="col">Miasto</th>
                <th scope="col">Adres</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>@Model.Id</td>
                <td>@Model.StationName</td>
                <td>@Model.City.Name</td>
                <td>@Model.AddressStreet</td>
            </tr>

        </tbody>
    </table>
</div>


<div class="space">
    <h4>Lista stanowisk pomiarowych</h4>
    <h5>W celu uzyskania szczegółowych danych pomiarowych na danym stanowisku prosimy wybrać numer stanowiska</h5>
</div>
<div class="card">
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">Numer stanowiska</th>
                <th scope="col">Badany parametr</th>
                <th scope="col">Symbol parametru</th>
                <th scope="col">Numer parametru</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var testStand in Model.TestStands)
            {

                <tr>
                    <td><a asp-controller="Data" asp-action="Data" asp-route-sensorId="@testStand.Id" asp-route-stationId="@testStand.StationId">@testStand.Id</a></td>

                    <td>@testStand.Param.ParamName</td>
                    <td>@testStand.Param.ParamFormula</td>
                    <td>@testStand.Param.IdParam</td>
                    <td></td>
                </tr>
            }
        </tbody>
    </table>
</div>


<div class="space">
    <h4>Jakość mierzonych parametrów powietrza</h4>
</div>
<div class="card">
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">Nazwa parametru</th>
                <th scope="col">Symbol parametru</th>
                <th scope="col">Poziom jakości parametru</th>
            </tr>
        </thead>
        <tbody>
            <partial name="_QualityLevel" />
        </tbody>
    </table>
</div>

<div class="space">
    <a class="btn btn-primary" asp-controller="Home" asp-action="Index">Wróć do listy stacji</a>
</div>